name: Dynamic_app
on:
  workflow_dispatch:

jobs:
  F32int_preval:
    runs-on: [self-hosted,Win2016]
    environment: Int_approval
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3
      # checkout~v3 checked out the files from the repo to the target machine. Run one time per workflow.
      - name: Run a one-line script
        run: |
           .\test-path.ps1 -mypath ${{ vars.CI_PROJECT_DIR }}
           echo "Path found . This is the F32int_prevalJob!"
           copy main-script.ps1 ${{ vars.CI_PROJECT_DIR }}
  F32int_prep:
    runs-on: [self-hosted,Win2016]
    needs: F32int_preval
    steps:
      - name: Run a Powershell script
        run: |
             echo "This is the F32int_audit job"
                         powershell -file ${{ vars.CI_PROJECT_DIR }}\main-script.ps1 -CI_PROJECT_DIR ${{ vars.CI_PROJECT_DIR }} -site "F24"  -sourcefile "source.txt" -LogFile "log.txt"
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dynamic-config
          path: |
            dynamic-config\dynamic-config-ci.yml
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
         name: dynamic-config
         path: ${{ vars.CI_PROJECT_DIR }}
                         
