name: CI_app
on:
  workflow_dispatch:

jobs:
  F32int_preval:
    runs-on: [self-hosted,Win2016]
    environment: Int_approval
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3
      # checkout~v3 checked out the files from the repo to the target machine. Run one time per workflow.
      - name: Run a one-line script
        run: echo "Step Approved. This is the F32int_prevalJob!"
  F32int_stage:
    runs-on: [self-hosted,Win2016]
    needs: F32int_preval
    steps:
      - name: Run a multi-line script
        run: |
          echo "This is the stage."
          echo "will stage files"
  F32int_rbprep:
    runs-on: [self-hosted,Win2016]
    needs: F32int_stage
    steps:
      - name: Run a one-line script
        run: echo "This is the F32int_rbprep job"

  F32int_audit:
    runs-on: [self-hosted,Win2016]
    needs: F32int_rbprep
    steps:
      - name: Run a one-line script
        run: |
             echo "This is the F32int_audit job"
             .\giveError.ps1
  F32int_deploy:
    runs-on: [self-hosted,Win2016]
    needs: F32int_audit
    steps:
      - name: Run a multi-line script
        run: |
          echo "Execute installSQLdb.ps1".
          .\installSQLdb.ps1
  F32int_hc:
    runs-on: [self-hosted,Win2016]
    needs: F32int_deploy
    steps:
      - name: Run a multi-line script
        run: |
          echo "Execute HC script".
          .\HC_installSQLdb.ps1
  F32int_rb:
    runs-on: [self-hosted,Win2016]
    timeout-minutes: 6
    if: ${{always()}}
    needs: [F32int_deploy, F32int_hc]
    steps:
      - name: Run a one-line script
        run: echo "Hello, Mike! This is the F32int_rb job - only run on failure"

      - name: Run a multi-line script
        run: |
          echo "This is the F32int_rb job - only run on failure".
          .\rollBack.ps1 -server F32_int -signalFilePath \\freenas\smb\mmgriffi\CICD -timeToWaitHrs 120
          #This script will create and check a file "<F32_int>_signal.txt" on a loop over a specified time
          #If admins updates the file to "NO" then rollback is skipped. If "YES" is added rollback is run and step completes.
          #If no response is given in the time, the job will complete with a failure without rollback.
          
  F32int_notify:
    runs-on: [self-hosted,Win2016]
    needs: F32int_deploy
    environment: Notify_approval
    steps:
      - name: Run a one-line script
        run: echo "Hello, Mike! This is the F32int_notify job"
